# Generated by Django 5.1.2 on 2024-10-22 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('street_no', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('street_no', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Places',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=100)),
                ('PSC', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('ICO', models.CharField(max_length=20, unique=True)),
                ('DIC', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('court_register', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='VAT',
            fields=[
                ('vat_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('vat_koeficient', models.FloatField()),
            ],
            options={
                'db_table': 'VATs',
            },
        ),
        migrations.CreateModel(
            name='Watermeter',
            fields=[
                ('watermeter_id', models.AutoField(primary_key=True, serialize=False)),
                ('sn', models.CharField(max_length=100, unique=True)),
                ('mbus_adr', models.CharField(max_length=100, unique=True)),
                ('recent_reading', models.FloatField(blank=True, null=True)),
                ('date_of_recent_reading', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Watermeters',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_start_day', models.DateTimeField()),
                ('contract_end_day', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='water.customer')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='water.provider')),
            ],
            options={
                'db_table': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='ProductContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.contract')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.product')),
            ],
            options={
                'db_table': 'Product_Contracts',
                'unique_together': {('product', 'contract')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='contracts',
            field=models.ManyToManyField(through='water.ProductContract', to='water.contract'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='water.vat'),
        ),
        migrations.CreateModel(
            name='WatermetersPlaces',
            fields=[
                ('watermeters_places_id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='water.place')),
                ('watermeter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='water.watermeter')),
            ],
            options={
                'db_table': 'Watermeters_Places',
                'unique_together': {('watermeter', 'place')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='watermeters_places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='water.watermetersplaces'),
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('water_consumption_id', models.AutoField(primary_key=True, serialize=False)),
                ('reading_datetime', models.DateTimeField()),
                ('reading_value', models.FloatField()),
                ('flag', models.CharField(choices=[('start', 'start'), ('end', 'end'), ('pending', 'pending')], max_length=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.contract')),
            ],
            options={
                'db_table': 'Water_Consumptions',
                'unique_together': {('contract', 'reading_datetime')},
            },
        ),
        migrations.CreateModel(
            name='WatermeterReadingHistory',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('watermeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.watermeter')),
            ],
            options={
                'db_table': 'watermeter_reading_history',
                'unique_together': {('watermeter', 'datetime')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('customer', 'watermeters_places')},
        ),
    ]
