# Generated by Django 5.1.2 on 2024-10-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]


    operations = [
        migrations.RunSQL(
            """
            -- Drop the existing trigger
            DROP TRIGGER IF EXISTS update_recent_reading_on_watermeters;

            -- Create a new trigger with both the old and new functionality
            CREATE TRIGGER update_recent_reading_on_watermeters
            AFTER UPDATE OF recent_reading ON Watermeters
            FOR EACH ROW
            WHEN NEW.recent_reading IS NOT NULL
            BEGIN
                -- Old functionality: Update the date_of_recent_reading in Watermeters
                UPDATE Watermeters
                SET date_of_recent_reading = CURRENT_TIMESTAMP
                WHERE watermeter_id = NEW.watermeter_id;

                -- Old functionality: Update the corresponding WaterConsumptions with the new recent_reading and date
                UPDATE Water_Consumptions
                SET reading_value = NEW.recent_reading,  -- Copy updated recent_reading to reading_value
                    reading_datetime = CURRENT_TIMESTAMP  -- Set current timestamp as reading_datetime
                WHERE contract_id = (
                    SELECT contract.contract_id  -- Find the associated contract_id
                    FROM Contracts AS contract
                    JOIN Watermeters_Places AS wp ON contract.watermeters_places_id = wp.watermeters_places_id
                    WHERE wp.watermeter_id = NEW.watermeter_id
                )
                AND flag = 'pending';  -- Only update where the flag is 'pending'
                
                -- New functionality: Insert a new record in watermeter_reading_history for the updated watermeter
                INSERT INTO watermeter_reading_history (watermeter_id, value, datetime)
                VALUES (NEW.watermeter_id, NEW.recent_reading, CURRENT_TIMESTAMP)
                ON CONFLICT(watermeter_id, datetime)
                DO NOTHING;  -- Ensure that duplicate records aren't created for the same timestamp
            END;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS update_recent_reading_on_watermeters;
            """
        )
    ]
