# Generated by Django 3.2.19 on 2024-10-23 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_auto_20241022_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=123.10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcontract',
            name='individual_price',
            field=models.DecimalField(decimal_places=2, default=123.10, max_digits=10),
            preserve_default=False,
        ),
    ]
