# Generated by Django 5.1.2 on 2024-10-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_update_trigger_update_recent_reading_on_watermeters'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set(),
        ),
    ]
